# Main
site_title: Help With Black Equity
site_subtitle: Projects to advance equity for the Black community
site_url: https://helpwithblackequity.herokuapp.com
share_image: https://helpwithblackequity.herokuapp.com/share-image.png

# Linked in the footer
contact_email: info@joinhelpwith.com
discord_link:
twitter_link:
facebook_link: https://www.facebook.com/deedapp
instagram_link: https://www.instagram.com/join.deed

# Site features
features_enabled:
  volunteer_directory: true
  resources: true
  office_hours: true
  success_stories: true
  for_profit_projects: true
  playbook: false
  projects_sort_by_filter: false

# Define how projects are organized. Slugs must not have spaces
project_categories:
  - name: Education
    slug: education
    body: Closing the gap in our education system
    project_types:
      - School-based
      - College affordability
      - STEM
      - Support HBCU’s
    color: cat-education
  - name: Social Justice
    slug: social-justice
    body: Directly impact social inequalities
    project_types:
      - Demonstrations
      - Policies
      - Voting & Elections
      - Criminal Justice
      - Income Inequality/Poverty
    color: cat-social-justice
  - name: Business Directory
    slug: business-directory
    body: Support Black business owners. If you are a BIPOC, please create a project and add your business!
    project_types:
      - Technology
      - Retail & Manufacturing
      - Professional Services
      - Food & Beverage
      - Health & Beauty
    color: cat-business-directory
  - name: Health
    slug: health
    body: Prevention, wellness and cures
    project_types:
      - Prevention
      - COVID-19
      - Access
      - Wellness
    color: cat-health
  - name: Wealth
    slug: wealth
    body: Employment and Funding
    project_types:
      - Jobs
      - Investors
      - Purchase Orders
      - Request for Proposal
      - Grant Writing
    color: cat-wealth

google_fonts_request: Lora&family=Roboto:wght@400;500;700

homepage_featured_projects_count: 12

# These are the skills that volunteers can have and projects can request.
volunteer_skills:
  - Analytics
  - Biology
  - Biotech
  - Community Outreach
  - Content
  - Customer
  - Data entry
  - Design
  - Donate
  - Funding
  - Helpdesk
  - Legal
  - Localization
  - Manufacturing
  - Marketing
  - Medicine
  - Mechanics & Electronics
  - Operations
  - PM
  - QA
  - Sales
  - Social Media
  - Software
  - Training Development
  - Volunteer vetting
  - Anything

# Availability windows that are suggested to volunteers
volunteer_availabilities:
  - 1-2 hours a day
  - 2-4 hours a day
  - 4+ hours a day
  - Only on Weekends
  - Full Time

# Options for how many volunteers a project might request
volunteers_needed_for_project:
  - 1-10
  - 10-50
  - 50-100
  - 100+

for_profit_types:
  - Black Businesses
  - Non-profit volunteering

project_statuses:
  - Just started
  - In progress
  - Launched

organization_statuses:
  - Non-profit
  - For-profit
  - Public Benefit Corporation
  - Not incorporated

# If a project has less than N volunteers
# it can ask to be highlighted.
max_volunteers_for_highlight_offer: 30

global_announcements:
#  - title: Helpful resources for your projects
#    sub_title: We wrote a playbook on how to manage volunteers, had some amazing panels, and gathered some deals for you.
#    cta_text: Browse resources
#    cta_url: /offers

events:
  - title: Running list of events and protests in the Bay Area
    sub_title: Get involved
    cta_text: View more
    cta_url: https://sf.funcheap.com/city-guide/list-upcoming-black-lives-matter-protests-sf-bay-area/

upcoming_events:
  # - title: COVID 19 Global Hackathon 2.0 - Social & Mental Health.
  #   sub_title: Hack on social issues and mental health with mentorship from nonprofits
  #   cta_text: Register here
  #   cta_url: https://covid-global-hackathon-2.devpost.com/
  #   month: July
  #   day: 3
  #   time: 10:00 AM

funding_resources:
  - cta_text: Black Angel Tech Fund
    cta_url: https://www.blackangeltechfund.com/
  - cta_text: Black Angels Miami
    cta_url: https://www.blackangels.miami/
  - cta_text: VCs pledging to fund Black owned companies
    cta_url: https://docs.google.com/spreadsheets/d/19O1BTO6p2tBbLJA9n-TTaxTCzIVT3hBMdbJUbBpFoLo/edit?ts=5ee416b9#gid=0
  - cta_text: Netflix will shift $100M of cash into Black-owned banks
    cta_url: https://www.bloomberg.com/news/articles/2020-06-30/netflix-will-shift-100-million-of-cash-into-black-owned-banks
  - cta_text: Salesforce, People, Philanthropy, Purchasing, and Policy
    cta_url: https://www.salesforce.com/company/news-press/stories/2020/6/racial-equality-and-justice/
  - cta_text: Microsoft spending $50 million on Black-owned small businesses
    cta_url: https://blogs.microsoft.com/blog/2020/06/23/addressing-racial-injustice/
  - cta_text: Google, $175 million commitment to help create economic opportunity
    cta_url: https://www.blog.google/inside-google/company-announcements/commitments-racial-equity/
  - cta_text: Sony Music Group announces $100 million-global-social-justice-fund
    cta_url: https://www.sonymusic.com/sonymusic/sony-music-group-announces-100-million-global-social-justice-fund/
  - cta_text: Comcast-announces-100-million-multiyear-plan-social-justice-and-equality
    cta_url: https://www.sonymusic.com/sonymusic/sony-music-group-announces-100-million-global-social-justice-fund/
  - cta_text: Mastercard Foundation works almost exclusively in Africa
    cta_url: https://mastercardfdn.org/foundation/
  - cta_text: Nike $40 million commitment to black community
    cta_url: https://news.nike.com/news/nike-commitment-to-black-community

partner_resources:
  # - name: AWS
  #   description: $10,000 in AWS credits for approved projects. Your project must be a corporate entity. Email helpwithcovid@gmail.com
  #   mail_to: helpwithcovid@gmail.com
  # - name: ClozeLoop
  #   description: |+
  #     Complete Sales Effectiveness Assessments for three companies we choose. The Sales Effectiveness Assessment is an evaluation of your company’s sales Strategy, Systems, Staff and Skills aligned with short and long-term revenue goals. The assessment provides a prioritized high-impact roadmap, and clear recommendations for growth.
  #     $2500 value.
  #   cta_link: https://clozeloop.typeform.com/to/ccPwVe

educational_articles:
  - cta_text: Standing United Deck
    cta_url: https://docs.google.com/presentation/d/1ltJmjs20m1rQGXPesYRi7zLq35mgWELQO8oFOrD1UlM/edit?usp=sharing
  - cta_text: A Letter to Corporate Leaders
    cta_url: https://medium.com/@aasu/a-letter-to-corporate-leaders-bd931d5326ab
  - cta_text: The forgotten struggle for civil rights in the northern U.S.
    cta_url: https://www.mprnews.org/story/2018/03/30/the-forgotten-struggle-for-civil-rights-in-the-northern-us
  - cta_text: Racism, whiteness, and burnout in antiracism movements - How white racial justice activists elevate burnout in racial justice activists of color in the United States
    cta_url: http://edchange.org/publications/White-Activists-Causing-Burnout-Racial-Justice-Activists-Gorski-Erakat.pdf
  - cta_text: Twitter thread on how to be an ally
    cta_url: https://insideoutincubator.us17.list-manage.com/track/click?u=7e29d413829f23aa51172807d&id=b8a8113b78&e=09341c6e55
  - cta_text: An article on how to be an ally at work this week
    cta_url: https://insideoutincubator.us17.list-manage.com/track/click?u=7e29d413829f23aa51172807d&id=a5caeab50e&e=09341c6e55
  - cta_text: Some advice on how to check on your Black friends
    cta_url: https://insideoutincubator.us17.list-manage.com/track/click?u=7e29d413829f23aa51172807d&id=4b908c852d&e=09341c6e55
  - cta_text: Visual representation to help you combat covert or “socially acceptable” forms of racism
    cta_url: https://insideoutincubator.us17.list-manage.com/track/click?u=7e29d413829f23aa51172807d&id=1ab4c3dfdd&e=09341c6e55
  - cta_text: 75 things White people can do for racial justice
    cta_url: https://insideoutincubator.us17.list-manage.com/track/click?u=7e29d413829f23aa51172807d&id=52d9136378&e=09341c6e55
  - cta_text: Barack Obama - How to make this moment the turning point for real change
    cta_url: https://medium.com/@BarackObama/how-to-make-this-moment-the-turning-point-for-real-change-9fa209806067
  - cta_text: Obama.org - Anguish and Action
    cta_url: https://www.obama.org/anguish-and-action/

educational_resources:
  - cta_text: 21 day racial equity and social justice challenge
    cta_url: https://www.ywcaofcleveland.org/2020-21-day-racial-equity-and-social-justice-challenge/
  - cta_text: Huge list of resources for being an ally (Anti-Racism and Allyship Resource Kit)
    cta_url: https://drive.google.com/file/d/1IqR6NzB6ifdNlpI2Vv5bQjYiega97W4w/view?usp=sharing
  - cta_text: Anti Racism Resources for White People
    cta_url: https://docs.google.com/document/u/1/d/1BRlF2_zhNe86SGgHa6-VlBO-QgirITwCTugSfKie5Fs/mobilebasic
  - cta_text: Broken Policing System - Hasan (video)
    cta_url: https://www.youtube.com/watch?v=km4uCOAzrbM
  - cta_text: the show must be paused
    cta_url: https://www.theshowmustbepaused.com/
  - cta_text: Use of force project
    cta_url: http://useofforceproject.org/#project

mental_health_resources:
  - cta_text: Virtual mental health resources supporting Black people right now
    cta_url: https://insideoutincubator.us17.list-manage.com/track/click?u=7e29d413829f23aa51172807d&id=26e96e5e76&e=09341c6e55

donation_resources:
  - cta_text: Campaign Zero
    cta_url: https://www.joincampaignzero.org/
  - cta_text: NAACP
    cta_url: https://www.naacp.org
  - cta_text: NAACP Legal Defense Fund
    cta_url: https://www.naacpldf.org/
  - cta_text: ACLU
    cta_url: https://www.aclu.org/
  - cta_text: Legal Rights Center
    cta_url: https://www.legalrightscenter.org/
  - cta_text: Northstar Health Collective
    cta_url: https://www.northstarhealthcollective.org/
  - cta_text: Real Justice PAC
    cta_url: https://realjusticepac.org/
  - cta_text: Open Philantrhopy Grants Database
    cta_url: https://www.openphilanthropy.org/giving/grants
  - cta_text: Color of Change
    cta_url: https://colorofchange.org/

media_kit:
  - name: HWC badges
    description: Badge to add to your launched page to gather more team members for your project
    cta_link: https://helpwithcovid.com/HWC-media-kit-badges.zip
  - name: HWC logos and wordmarks
    description: Logos, wordmark and banner for any media coverage about HWC
    cta_link: https://helpwithcovid.com/HWC-media-kit-logos.zip
