colors:
  primary: tailwind/ui/gray
  secondary: tailwind/ui/yellow
  accent:
    default: '#FFCE3D'
    hover: '#ffe085'
    text: '#000000'
    border: '#8e4b10'
    active: '#8e4b10'
    focus: '#8e4b10'
    sub_navbar_bg: '#3D3D3D'
    sub_navbar_text: '#ffffff'
    filters_navbar_bg: '#3D3D3D'
    filters_navbar_text: '#ffffff'
  categories:
    cat-technology: '#8921DC'
    cat-retail-and-manufacturing: '#2987DE'
    cat-professional-services: '#12CFA1'
    cat-food-and-beverage: '#F82B2B'
    cat-business-directory: '#27DDDA'
    cat-founders: '#DDC827'
    cat-wealth: '#DD7627'
              
              
              
